version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
